### PR TITLE
PDA-118: Support groups on task list endpoint

### PR DESCRIPTION
**Pull request by werbth**

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by werbth** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Review by ffleandro — APPROVED** [review]

**Review by ffleandro — DISMISSED** [review]
There should be test cases for a search with groups

**Comment by werbth** [comment]
> There should be test cases for a search with groups

Groups here are like users, which are not directly dependent on the task attributes and we are not testing here. On the entando-redhatpam-engine project we are testing if the groups are being passed to the API call. Testing groups here is like testing the AuthenticatedUser attribute.

**Review by BrenoQVDS — APPROVED** [review]

**Review by BrenoQVDS — APPROVED** [review]

**Review by BrenoQVDS — APPROVED** [review]

**Pull request merged**
