### PR TITLE
PDA-72 Baseline implementation for dual time series summary data and …

### PR DESCRIPTION
**Pull request by joewhite101**
This commit refactors the Summary framework to support summaries with a different SummaryType annotation so that the front end can identify available summaries by their SummaryType and pick the appropriate one to render. For example, there may be many implementations of the ValuePercentage or DualTimeSeries types that can be selected to render into the graphs.

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Comment by entando-service** [comment]
All is well

**Review by joewhite101 — COMMENTED** [review]
Approving for future review so we can integrate.

**Review by werbth — APPROVED** [review]

**Pull request merged**
